modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.1839880496263504
  - -0.18925394117832184
  - 0.2823812663555145
  - 0.1749868243932724
  - -0.5116972327232361
  - 0.029342899098992348
  - -0.001680792891420424
  - -0.7261402606964111
  - -0.3983229398727417
  - -0.01437010895460844
  - 0.0603029727935791
  - 0.0029314772691577673
  - 3.7918448448181152
  - 0.2389020025730133
  - 1.1746517419815063
  - 0.3183218240737915
  - -0.6498419046401978
  - 0.45837968587875366
  - 0.5268056392669678
  - -0.199595645070076
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov_c + st_zones_income_6_hh_sum_10_min_sov_c
    + st_zones_jobs_0_sum_5_min_sov_c + st_zones_jobs_1_sum_5_min_sov_c + st_zones_jobs_2_sum_5_min_sov_c
    + st_zones_jobs_3_sum_5_min_sov_c + st_zones_jobs_4_sum_5_min_sov_c + st_zones_jobs_5_sum_5_min_sov_c
    + st_zones_total_jobs_sum_20_min_sov_c - 1
  name: elcm_48453_blocks_5_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "48453")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "48453") & (agg_sector=="5")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
