constraints:
  cohabitate:
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  married:
  - 0
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
model_coeffs:
  cohabitate:
  - -8.0
  - 3.352391
  - 2.889173
  - 2.232864
  - -3.329631
  - -0.548444
  - -0.770682
  - -0.209583
  - -0.670861
  - -0.139049
  married:
  - -8.0
  - 1.347319
  - 0.808832
  - -0.750587
  - 0.550044
  - -0.625874
  - -0.10176
  - 0.727
  - 1.049543
  - -0.603113
spec_names:
- intercept
- agebin2
- agebin3
- agebin4
- gender2
- employbin2
- employbin3
- edubin2
- edubin3
- race_blk
