modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: counties
  choice_column: lcm_county_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - 0.1736513078212738
  - -0.08376353234052658
  - -0.5504667162895203
  - 1.3137925863265991
  max_iter: null
  model_expression: st_mean_bg_median_value + st_total_hh + st_total_jobs + st_total_units
    - 1
  name: rdplcm_county_pf
  out_alt_filters: (vacant_du_spaces > 0)
  out_alternatives: null
  out_chooser_filters: (lcm_county_id == "-1")
  out_choosers: null
  out_column: lcm_county_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
